{% set name = "skywalking-eyes" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/skywalking-eyes/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 10846c1540d7e9a035e4bf19e752c725c19db01d0add0b061f1de09353be2e46

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - skywalking-eyes --help

about:
  home: https://github.com/apache/skywalking-eyes
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Tool to check and fix license headers and resolve dependency licenses
  dev_url: https://github.com/apache/skywalking-eyes

extra:
  recipe-maintainers:
    - danielnachun
