schema_version: 1

context:
  version: "0.9.0"

package:
  name: skywalking-eyes
  version: ${{ version }}

source:
  url: https://github.com/apache/skywalking-eyes/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 09659bf028cef97bcd2d877c67ccde2df92c3dbaeb65d975cac5920a5db7fff6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - skywalking-eyes --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Tool to check and fix license headers and resolve dependency licenses
  homepage: https://github.com/apache/skywalking-eyes
  repository: https://github.com/apache/skywalking-eyes

extra:
  recipe-maintainers:
    - danielnachun
